MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Models/Race.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using MVC_TeddySmith_RunGroup.Data.Enum;

namespace MVC_TeddySmith_RunGroup.Models
{
    public class Race
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string? Image { get; set; }
        public DateTime? StartTime { get; set; }
        public int? EntryFee { get; set; }
        public string? Website { get; set; }
        public string? Twitter { get; set; }
        public string? Facebook { get; set; }
        public string? Contact { get; set; }
        [ForeignKey("Address")]
        public int AddressId { get; set; }
        public Address Address { get; set; }
        public RaceCategory RaceCategory { get; set; }
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }
    }
}

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using MVC_TeddySmith_RunGroup.Data;
using MVC_TeddySmith_RunGroup.Interfaces;
using MVC_TeddySmith_RunGroup.Models;
using MVC_TeddySmith_RunGroup.Repository;
using MVC_TeddySmith_RunGroup.ViewModels;
using static System.Reflection.Metadata.BlobBuilder;

namespace MVC_TeddySmith_RunGroup.Controllers
{
    public class RaceController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public RaceController(ApplicationDbContext context, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor; 
        }

        public IActionResult Index()
        {
            var race = _context.Races.ToList();
            return View(race);
        }

        public IActionResult Detail(int id)
        {            
            Race race = _context.Races.Include(a => a.Address).FirstOrDefault(c => c.Id == id); 
            return View(race);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createRaceViewModel = new CreateRaceViewModel
            {
                AppUserId = curUserId,
            };
            return View(createRaceViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateRaceViewModel raceVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = await _photoService.AddPhotoAsync(raceVM.Image);
                   var race = new Race
                    {
                        Title = raceVM.Title,
                        Description = raceVM.Description,
                        Image = result.Url.ToString(),
                        AppUserId = raceVM.AppUserId,
                        Address = new Address
                        {
                            Street = raceVM.Address.Street,
                            City = raceVM.Address.City,
                            State = raceVM.Address.State,
                        }
                    };
                    _context.Add(race);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Photo upload failed");
                }
                return View(raceVM);
            }
            catch (Exception)
            {
                return View(raceVM);
            }

        }


        public async Task<IActionResult> Edit(int id)
        {

            var race = await _context.Races.FindAsync(id); 
            if (race == null) return View("Error");
            var raceVM = new EditRaceViewModel
            {
                Title = race.Title,
                Description = race.Description,
                AddressId = (int)race.AddressId,
                Address = race.Address,
                Url = race.Image,
                RaceCategory = race.RaceCategory
            };
            return View(raceVM);
        }


        // !!!!!!!!!!!!!!!!!!!!!!!!!!  TRACKİNG HATASInı REPOSİTORYSİZ(INTERFACES(IClubRepository)) ÇÖZülMÜŞ HALİ !!!!!!!!!!!!!!!!!!!!!!!
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditRaceViewModel raceVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Faild to edit club");
                return View("Edit", raceVM);
            }
            var userRace = await _context.Races.FindAsync(id);

            if (userRace != null)
            {
                //  RESMİ SİLİYOR
                try
                {
                    await _photoService.DeletePhotoAsync(userRace.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(raceVM);
                }
                // RESİM YÜKLÜYOR
                _context.ChangeTracker.Clear(); //sadece bunu yazarsam tracking hatası vermedi ama edit de yapmadı _context.Update(race); bundan sonra save changes diyim ki kaydosun sqle
                var photoResult = await _photoService.AddPhotoAsync(raceVM.Image);  //------------------
                _context.SaveChanges();


                var race = new Race
                {
                    Id = id,
                    Title = raceVM.Title,
                    Description = raceVM.Description,
                    Image = photoResult.Url.ToString(),
                    AddressId = raceVM.AddressId,
                    Address = raceVM.Address,
                };
               _context.Update(race);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(raceVM);
            }





        }

    }
}

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Race/Create.cshtml
@using MVC_TeddySmith_RunGroup.Data.Enum
@using MVC_TeddySmith_RunGroup.ViewModels
@model CreateRaceViewModel

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <input type="hidden" id="AppUserId" name="AppUserId" asp-for="AppUserId" />
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RaceCategory">Race Category</label><br />
        <select asp-for="RaceCategory" asp-items="@Html.GetEnumSelectList<RaceCategory>()" class="form-control form-control">
            <option>--Select--</option>
        </select>
        <span asp-validation-for="RaceCategory" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.Street">Street</label>
        <input asp-for="Address.Street" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.City">City</label>
        <input asp-for="Address.City" class="form-control" placeholder="City">
        <span asp-validation-for="Address.City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.State">State</label>
        <input asp-for="Address.State" class="form-control" placeholder="State">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Race/Detail.cshtml
@model Race
<!-- Page Content -->
<div class="container">

    <!-- Portfolio Item Heading -->
    <h1 class="my-4">
        Page Heading
        <small>Secondary Text</small>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <img class="img-fluid" src="@Model.Image" alt="">
        </div>

        <div class="col-md-4">
            <h3 class="my-3">@Model.Title</h3>
            <p>@Model.Description</p>
            <h3 class="my-3">Location</h3>
            <ul>
                <li>@Model.Address.City</li>
                <li>@Model.Address.State</li>
                <li>@Model.RaceCategory</li>
            </ul>
        </div>

    </div>
    <!-- /.row -->
    <!-- Related Projects Row -->
    <h3 class="my-4">Related Projects</h3>

    <div class="row">

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Race/Edit.cshtml
@using MVC_TeddySmith_RunGroup.Data.Enum
@using MVC_TeddySmith_RunGroup.ViewModels
@model EditRaceViewModel

<form method="post" asp-action="Edit" enctype="multipart/form-data">
    <input type="hidden" value="AddressId" id="AddressId" />
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RaceCategory">Club Category</label>
        <select asp-for="RaceCategory" asp-items="@Html.GetEnumSelectList<RaceCategory>()" class="form-control">
            <option selected="selected" value="">--Select--</option>
        </select>
        <span asp-validation-for="RaceCategory" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.Street">Street</label>
        <input asp-for="Address.Street" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.City">City</label>
        <input asp-for="Address.City" class="form-control" placeholder="City">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.State">State</label>
        <input asp-for="Address.State" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Race/Index.cshtml
@model IEnumerable<Race>


<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Race" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                                    { 
                                    <a type="btn btn-success" asp-controller="Race" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>                                  
                                    }
                                </div>
                                <small class="text-muted">@item.RaceCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>