MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Models/Club.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using MVC_TeddySmith_RunGroup.Data.Enum;

namespace MVC_TeddySmith_RunGroup.Models
{
    public class Club
    {
        //primary key is parent(only one person can be a parent), foreignKey is child.
        //Only one primarykey can exist but multiple foreignkey could be exist
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
       
        [ForeignKey("Address")]
        public int? AddressId { get; set; }  // bu olmadan yani foreign key olmadan da olur ama sonrasında kontrol etmek daha zor olur   
        public Address? Address { get; set; }  //AddressId ile one to many ilişkisi var (adress classı ile)
      
        public ClubCategory ClubCategory { get; set; }
    
        
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }  //identity framework kullandığımız için appuser ıd si string 
        public AppUser? AppUser { get; set; }
    }
}

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_TeddySmith_RunGroup.Data;
using MVC_TeddySmith_RunGroup.Models;
using static System.Net.Mime.MediaTypeNames;
using System.Net.Sockets;
using System.Reflection.Metadata;
using MVC_TeddySmith_RunGroup.Interfaces;
using MVC_TeddySmith_RunGroup.ViewModels;
using CloudinaryDotNet.Actions;

namespace MVC_TeddySmith_RunGroup.Controllers
{
    public class ClubController : Controller
    {
        //private readonly ApplicationDbContext _clubRepository;  //----------------- önceden bunu kullanıyoduk ama repository falan gelince alttakini kullanmaya başladık
        private readonly IClubRepository _clubRepository;
        private readonly IPhotoService _photoService;
        //bunu yazdıktan sonra inject ediyoruz (context üsütne geldikten sonra kenardaki süpürge gibi olan şeye tıklıyoruz create field yazana tıklıyoruz
        //private readonly ApplicationDbContext context; kodu çıkıyor 

        private readonly IHttpContextAccessor _httpContextAccessor;    //adding the ability for the server to return the app user id 



        public ClubController(IClubRepository clubRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)  //ApplicationDbContext this our data base. this controlling our access to our date base (ama IClubRepository clubRepository ile değiştirdik sonradan)
        {
            _clubRepository = clubRepository;  //---------- önceden _context = context idi
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        //controller are build our url !!!!!!!!!!1
        //controller control where is entering but doesnt control this view is being seen (return view diyor ya) o yüzden
        //views folderına gidip club view ı oluşturmamız da gerekiyor (view folderında Index olan burdaki index le aynı isimde olması için değiştirmedik)

        // An ActionResult is a return type of a controller method, also called an action method, and serves as the base class for *Result classes.
        // Action methods return models to views, file streams, redirect to other controllers, or whatever is necessary for the task at hand.
        //It specifies how a response is going to be given for a Specific Request.
        public async Task<IActionResult> Index() // ------------ önceden IActionResult Index() di sadece
        {
            //so you coming in and it give you the model (var clubs...) and its returning the view ( return View(clubs) )
            //_clubRepository.Clubs -> this is bringing our whole databese to program. ToList -> we need to call this to actualy execute the sql so this gonna build whose query its gonna send it to the database
            IEnumerable<Club> clubs = await _clubRepository.GetAll();  // ----------------------- önceden var clubs = _clubRepository.ToList() idi           

            //List<Club> yazabiliriz var yerine
            //(ama clubs listesinin içi boşsa null hatası alır o yüzden var daha sağlıklı)
            return View(clubs);  //your person is coming in and hitting this controller and this is going to be whats returned to the viewer 
            //(return viewer yerine başka şeyler de döndürülebilir uygulamanın isteklerine göre)

            //now we drop our model off to view and now we need to go back to the actual view(view-club-ındex) so our view actually see our data -> @model IEnumerable<Club>
        }


        public IActionResult Detail(int id) 
        {
            //join table yaptığımızda hep bir tablodan diğerine geçiş yap için include kullanmalıyız yoksa kod hata veriyor view club details da
            //include belirtilen değerin dizi öğelerinde olup olmadığını test eder. Metod, belirtilen değerin içinde geçmesini değil, tam olarak eşleşip eşleşmediğini kontrol eder.
            //clubs dediğimiz table (yani onun ismi dikkat)
            
            var club = _clubRepository.GetByIdAsync(id);  ////----------------------------- önceden
                                                          //var... = ...Clubs.Include(a => a.Address).FirstOrDefault(c => c.Id==id) idi
            return View(club);
        }


        [HttpGet]
        public IActionResult Create()
        {
            //we need to get the user id so we need the get that form the server 
            //before it shows the web page to the user it going to pull http context and its going to get that user of the http context 
            // BUT WHEN YOU PULL THE HTTP CONTEXT you get a huge object that hard to manage so its just better to abstract this away so you can just quickly grab the value that you want you dont have to worry about digging through this massive object ---> create a class called ClaimsPrincipalExtensions
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId(); //GetUserId() this comes from ClaimsPrincipalExtensions -> with that its going to get our actually id and we dont have to go to the database (much more easier). itsgonna get string so on the view model 


            //we are gonna use our view model and we are going to pass our currently user id 
            var createClubViewModel = new CreateClubViewModel
            {
                AppUserId = curUserId,
            };

            
            return View(createClubViewModel); 
        }


        //uploading photo: we are not going to directly upload our database.the is a lot of limitations on that.espaiclly social media we are going to have to outsource our photo to photo bucket, bucket, blob database ext...essentially we're going to outsource this anothor piece of 100 free software like Azure, Cloudinary. Cloudinary is good alternative for small projects or when you're building mvp with azure is a little bit more complicated
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateClubViewModel clubVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //  return View(club);  //resim eklemeden önce sadece bunu diyorduk ama eklemek istediğimiz için değişiklikler yaptık. normalde metod (Club club) değeri alıyodu sadece

                    //there is different types of ways that you can control passing state in our vies but whenever your views more and more complicated all of the times it just makes sense to create view models for our views (we add ViewModels folder and on this we created a class called CreateClubViewModel)
                    var result = await _photoService.AddPhotoAsync(clubVM.Image);

                    //we could use outo mapper for this but auto mapper is going to way overkill in this situation 
                    //yani burda kullanıcın siteden girdiği modeli kaydettiğimiz CreateClubViewModelden alıp veri tabanımız olan asıl veri tabanımıza kaydediyoruz
                    var club = new Club //Club tablomuzdan club isimliyeni bir obje oluşturuyoruz ki veri tabınımıza çektiklerimizi kaydedelim
                    {
                        Title = clubVM.Title,
                        Description = clubVM.Description,
                        Image = result.Url.ToString(), //we are going to return the result that we get back from cloudinary 
                        AppUserId = clubVM.AppUserId, //kullanıcılara göre club,race falan göstermeden önvce bu yoktu ama artık kullanıcılar da club create edeb için hangi kullanıcı bunu yapmaya çalışıyo bilmemiz lazım o yüzden get creati ile kullaıcı id sini almıştık şimdi onu model e gönderiyoruz
                        Address = new Address
                        {
                            Street = clubVM.Address.Street,
                            City = clubVM.Address.City,
                            State = clubVM.Address.State,
                        }
                    };
                     _clubRepository.Add(club);
                    _clubRepository.Save(); //veri tabanımıza kaydedioruz ------------------önceden savechanges di
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Photo upload failed");
                }
                return View(clubVM);
            }
            catch (Exception)
            {
                return View(clubVM);
            }
        }


        public async Task<IActionResult> Edit (int id) //create den farkı id alması 
        {
           
            var club = await _clubRepository.GetByIdAsync(id);  //----------------------------- önceden .Clubs.FindAsync idi
            if (club == null) return View("Error");
            var clubVM = new EditClubViewModel
            {
                Title = club.Title,
                Description = club.Description,
                AddressId = (int)club.AddressId,
                Address = club.Address,
                Url = club.Image,
                ClubCategory = club.ClubCategory
            };
            return View(clubVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditClubViewModel clubVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Faild to edit club");
                return View("Edit",clubVM);
            }
            var userClub = await _clubRepository.GetByIdAsyncNoTracking(id);   //----------------------------- önceden .Clubs.FindAsync idi
           
            if (userClub !=null)
            { 
                //  RESMİ SİLİYOR
                try
                {
                    await _photoService.DeletePhotoAsync(userClub.Image); //userclub boş değilse önceki fotoğrafı silicek
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(clubVM);
                }

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Club/Create.cshtml
@using MVC_TeddySmith_RunGroup.Data.Enum
@using MVC_TeddySmith_RunGroup.ViewModels
@model CreateClubViewModel

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <input type="hidden" id="AppUserId" name="AppUserId" asp-for="AppUserId" /> @* hidden alanlar ekliyoruz ki her kullancıcı club oluşturamasın,silemesin... gibi (formun içine koyuyoruz yoksa çalışmaz)*@
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control"  placeholder="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ClubCategory">Club Category</label><br />
        <select asp-for="ClubCategory" asp-items="@Html.GetEnumSelectList<ClubCategory>()" class="form-control form-control">
            <option>--Select--</option>
        </select>        
        <span asp-validation-for="ClubCategory" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.Street">Street</label>
        <input asp-for="Address.Street" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.City">City</label>
        <input asp-for="Address.City" class="form-control" placeholder="City">
        <span asp-validation-for="Address.City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.State">State</label>
        <input asp-for="Address.State" class="form-control" placeholder="State">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Club/Delete.cshtml
@using MVC_TeddySmith_RunGroup.Data.Enum
@model Club

<h1>Are you sure you want to delete this club?</h1>

<form method="post" asp-action="Delete" enctype="multipart/form-data">
    <input type="hidden" value="AddressId" id="AddressId" />
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ClubCategory">Club Category</label>
        <select asp-for="ClubCategory" asp-items="@Html.GetEnumSelectList<ClubCategory>()" class="form-control">
            <option selected="selected" value="">--Select--</option>
        </select>
        <span asp-validation-for="ClubCategory" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.Street">Street</label>
        <input asp-for="Address.Street" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.City">City</label>
        <input asp-for="Address.City" class="form-control" placeholder="City">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.State">State</label>
        <input asp-for="Address.State" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>

    </div>
</form>
<div class="form-group">
    <form action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Confirm" class="btn btn-danger float-right mt-3" />
    </form>
</div>

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Club/Detail.cshtml
@model Club
<!-- Page Content -->
<div class="container">

    <!-- Portfolio Item Heading -->
    <h1 class="my-4">
        Page Heading
        <small>Secondary Text</small>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <img class="img-fluid" src="@Model.Image" alt="">
        </div>

        <div class="col-md-4">
            <h3 class="my-3">@Model.Title</h3>
            <p>@Model.Description</p>
            <h3 class="my-3">Location</h3>
            <ul>
                <li>@Model.Address.City</li>
                <li>@Model.Address.State</li>
                <li>@Model.ClubCategory</li>
            </ul>
        </div>

    </div>
    <!-- /.row -->
    <!-- Related Projects Row -->
    <h3 class="my-4">Related Projects</h3>

    <div class="row">

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Club/Edit.cshtml
@using MVC_TeddySmith_RunGroup.Data.Enum
@using MVC_TeddySmith_RunGroup.ViewModels
@model EditClubViewModel

<form method="post" asp-action="Edit" enctype="multipart/form-data">
    <input type="hidden" value="AddressId" id="AddressId" />  @*when we add our adress we need to add hidden field couse we need to store adress id*@
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ClubCategory">Club Category</label>
        <select asp-for="ClubCategory" asp-items="@Html.GetEnumSelectList<ClubCategory>()" class="form-control">
            <option selected="selected" value="">--Select--</option>
        </select>
        <span asp-validation-for="ClubCategory" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.Street">Street</label>
        <input asp-for="Address.Street" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.City">City</label>
        <input asp-for="Address.City" class="form-control" placeholder="City">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.State">State</label>
        <input asp-for="Address.State" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MVC_TeddySmith_RunGroup/MVC_TeddySmith_RunGroup/Views/Club/Index.cshtml
@model IEnumerable<Club>  //Club modelini getiriyoruz.  list gönderdğimiz için IEnumrable (if we were returning 1 club we dont need ıenum...).now we are gonna return club model with foreach  <div class="row"> altına 




<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
             <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">  
                    <div class="card-body">
                        <p class="card-text">@item.Title</p>  
                                <p class="card-text">@item.Description</p>    
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))  @*admin -> this has o match perfectly with the  data-user role *@
                                    {
                                <a asp-controller="Club" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                <a asp-controller="Club" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>

                                    }
                            </div>
                                    <small class="text-muted">@item.ClubCategory</small>    
                        </div>
                    </div>
                </div>
            </div>
            }

            
        </div>
    </div>
</div>